default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: vigneshg
  password: vigneshg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hfw_backend_development

test:
  <<: *default
  database: hfw_backend_test
 
production:
  <<: *default
  database: hfw_backend_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
